export enum REPORT_STATUS {
    PENDING = 'PENDING',
    SCHEDULED = 'SCHEDULED',
    COLLECTED = 'COLLECTED',
}

export enum CATEGORY {
    RECYCLABLE = 'RECYCLABLE',
    ORGANIC = 'ORGANIC',
    ELECTRONIC = 'ELECTRONIC',
    CONSTRUCTION = 'CONSTRUCTION',
    MEDICAL = 'MEDICAL',
    OTHER = 'OTHER',
}
